### ISSUE TITLE
eloBLOCK B510 SetModeOverride accepted but has no effect on BAI00 SW0107/HW7503

### ISSUE THREAD

**Issue by MarkBovee** [MarkBovee/vaillant-ebus#111]
## Summary

The eloBLOCK VE 28 read-side support is confirmed working in #103. The B510 `SetModeOverride` control path remains unconfirmed on a real BAI00 installation.

## Hardware

- Device: Vaillant eloBLOCK VE 28
- Scan: `MF=Vaillant;ID=BAI00;SW=0107;HW=7503`
- ebusd: `26.1.26.1`

## Observed

The runtime definition is accepted:

```text
ebusctl define -r "wi,bai,SetModeOverride,Operation Mode,,08,B510,00,hcmode,,UCH,,,,flowtempdesired,,D1C,,,,hwctempdesired,,D1C,,,,hwcflowtempdesired,,UCH,,,,setmode1,,UCH,,,,disablehc,,BI0,,,,disablehwctapping,,BI1,,,,disablehwcload,,BI2,,,,setmode2,,UCH,,,,remoteControlHcPump,,BI0,,,,releaseBackup,,BI1,,,,releaseCooling,,BI2"
done
```

The write is accepted without a response body:

```text
ebusctl w -c bai SetModeOverride "0;55;45;-;-;0;0;0;-;0;0;0"
empty
```

Afterwards:

```text
FlowTempDesired = 0.00
StorageTempDesired = 37.00
```

The Home Assistant `vaillant_ebus.set_mode_override` service also completes without an error, but no active heating starts and the desired flow temperature remains unchanged.

## Investigation needed

- Confirm the B510 payload layout for BAI00 SW0107/HW7503.
- Determine whether the write requires a different master/slave address, field encoding, or controller mode.
- Check whether `empty` is an accepted write response for this firmware or indicates no effect.
- Validate a safe read-back or observable state transition before changing the integration.

The read-side support remains complete and is covered by the existing eloBLOCK fixture and tests in #103.

**Comment by MarkBovee** [comment]
## Additional Evidence: Product-Specific BAI Configuration

A community guide for Vaillant eloBLOCK systems provides useful context for the current `SetModeOverride` investigation:

https://gist.github.com/stalniy/5ec118d50f7b8c0a87514e9085418b64

The guide uses a product-specific BAI include selected by the `scan.08` product ID. It defines `SetModeOverride` in that product-specific configuration and notes that the override is temporary and must be refreshed periodically.

It also recommends using the normal writable registers for boiler control where available:

```text
HeatingSwitch
HwcSwitch
```

This may explain why the generic runtime definition is accepted on the BAI00 SW0107/HW7503 system but has no observable effect. The write response is empty, and the desired flow temperature remains unchanged.

## Next Data Needed

Please run the following on the eloBLOCK ebusd instance and share the output:

```text
ebusctl find -d -v -c scan.08 id
ebusctl info
ebusctl find -v -c bai SetModeOverride
ebusctl find -v -c bai HeatingSwitch
ebusctl find -v -c bai HwcSwitch
```

If `HeatingSwitch` and `HwcSwitch` are available, also report their current values:

```text
ebusctl read -c bai HeatingSwitch
ebusctl read -c bai HwcSwitch
ebusctl read -c bai FlowTempDesired
ebusctl read -c bai StorageTempDesired
```

The product ID and writable-register output will show whether this installation needs a product-specific BAI layout or whether `SetModeOverride` uses a different payload on this firmware. No integration code change is proposed until those values are confirmed.

**Comment by MarkBovee** [comment]
Please update to **v1.7.0** and export a new discovery dump using the integration service:

```yaml
action: vaillant_ebus.export_discovery_dump
data:
  grab_duration: 30
```

The new dump format keeps the original raw `find` and grab data and also adds:

- Normalized discovered, mapped, unavailable, and disabled registers.
- Meaningful before/after register changes.
- Grouped known and unknown telegrams.
- Unique requests and responses for unknown telegrams.
- Integration and ebusd version metadata.

For the B510 investigation, please also include the output of these commands from the eloBLOCK ebusd instance:

```text
ebusctl find -d -v -c scan.08 id
ebusctl info
ebusctl find -v -c bai SetModeOverride
ebusctl find -v -c bai HeatingSwitch
ebusctl find -v -c bai HwcSwitch
```

If `HeatingSwitch` and `HwcSwitch` are available, please include their current values as well:

```text
ebusctl read -c bai HeatingSwitch
ebusctl read -c bai HwcSwitch
ebusctl read -c bai FlowTempDesired
ebusctl read -c bai StorageTempDesired
```

The product ID and structured telegram data will show whether this system needs a product-specific BAI layout or whether `SetModeOverride` uses a different payload on this firmware.

**Comment by waphbs** [comment]
Hi @MarkBovee,

I have updated to v1.8.0 and exported the new discovery dump file (attached).

Here is the complete output from the requested ebusctl commands on my eloBLOCK VE 28 instance:

Plaintext
[root@b4d7ad18-ebusd:/# ebusctl find -d -v -c scan.08 id
ebusctl info
ebusctl find -v -c bai SetModeOverride
ebusctl find -v -c bai HeatingSwitch
ebusctl find -v -c bai HwcSwitch
ebusctl read -c bai HeatingSwitch
ebusctl read -c bai HwcSwitch
ebusctl read -c bai FlowTempDesired
ebusctl read -c bai StorageTempDesired
Scan.08 Id = prefix=21;year=19;week=26;product=0010023742;supplier=3100;counter=005232;suffix=N8

version: ebusd 26.1.26.1
device: 192.168.10.112:9999, TCP, enhanced, firmware 1.1[6104].1[6104]
access: *
signal: acquired
symbol rate: 23
max symbol rate: 112
min arbitration micros: 1
max arbitration micros: 79
min symbol latency: 5
max symbol latency: 50
scan: finished
reconnects: 0
masters: 3
messages: 257
conditional: 3
poll: 191
update: 10
address 00: master #1
address 03: master #11
address 08: slave #11, scanned "MF=Vaillant;ID=BAI00;SW=0107;HW=7503", loaded "vaillant/bai.308523.inc", "vaillant/08.bai.csv"
address 31: master #8, ebusd
address 36: slave #8, ebusd

ERR: element not found

bai HeatingSwitch = value=on

bai ExternalHwcSwitch = value=off
bai HwcSwitch = value=on

on

on

0.00

37.00

[discovery_dump_2026-09-11_193100.yaml](https://github.com/user-attachments/files/32104649/discovery_dump_2026-09-11_193100.yaml)

]
Hope this data helps determine whether product-specific scan.08 handling or HeatingSwitch / HwcSwitch registers are the key to controlling the VE 28!

**Comment by MarkBovee** [comment]
Thanks, this is very helpful!

The output confirms that SetModeOverride is not available in the BAI configuration on your VE 28, while HeatingSwitch and HwcSwitch are available and working.

The discovery dump is also exactly what we needed. I’ll investigate the product-specific configuration and see what the correct way is to control the VE 28.

Thanks for providing all this data!

**Comment by MarkBovee** [comment]
Merged https://github.com/MarkBovee/vaillant-ebus/pull/122 Will create a release today

**Comment by MarkBovee** [comment]
**eloBLOCK VE 28 (BAI00 SW0107 / HW7503) follow-up in v1.8.1** — https://github.com/MarkBovee/vaillant-ebus/releases/tag/v1.8.1

The BAI metadata from the merged PR is in this release, and v1.8.1 adds on/off control:

- `Heating Switch` and `DHW Switch` are now exposed as switch entities.
- The integration redefines them writable on the BAI `B509` message (ID `F203` / `F303`), which is where the upstream product-specific BAI includes declare them writable (`wi_1`). The generic `bai.308523.inc` declares them read-only, which is why they could only be read.

The community eloBLOCK guide uses exactly these two registers as the reliable control path, and notes that `SetModeOverride` is temporary and must be re-sent. On your unit `SetModeOverride` is not present in the loaded BAI configuration at all.

Please update to v1.8.1, restart or reload, and test:

1. Toggle `Heating Switch` and `DHW Switch` from Home Assistant and check whether the boiler reacts.
2. Run `ebusctl find -v -c bai HeatingSwitch` and `ebusctl find -v -c bai HwcSwitch` and confirm they now report as writable.
3. If a toggle has no effect, attach `ebusctl info` and the raw `ebusctl read -c bai HeatingSwitch` and `ebusctl read -c bai HwcSwitch` output.

One honest caveat: the `B509` write layout is verified against upstream and the community guide, but not yet against your specific BAI00 / SW0107 unit, so your test result decides it. If it does not work, I will look at the raw write telegram.

**Comment by waphbs** [comment]
Hi @MarkBovee,

I updated to v1.8.2 and tested the new switch entities on my BAI00 SW0107 / HW7503 unit:

Read / State Syncing: Working perfectly. Operating the controls directly on the physical boiler updates the Heating Switch and DHW Switch states in Home Assistant in real time.

Write / Control: Toggling the switches in Home Assistant has no effect on the boiler, and manual terminal write commands fail/do not trigger a physical reaction.

Here is the raw ebusctl diagnostic output for raw write telegram investigation:

Plaintext
[root@b4d7ad18-ebusd:/# ebusctl find -v -c bai HeatingSwitch
ebusctl find -v -c bai HwcSwitch
ebusctl read -c bai HeatingSwitch
ebusctl read -c bai HwcSwitch
ebusctl write -c bai HeatingSwitch on
ebusctl info
bai HeatingSwitch = value=off

bai ExternalHwcSwitch = value=off
bai HwcSwitch = value=off

off

off

ERR: element not found

version: ebusd 26.1.26.1
device: 192.168.10.112:9999, TCP, enhanced, firmware 1.1[6104].1[6104]
access: *
signal: acquired
symbol rate: 19
max symbol rate: 86
min arbitration micros: 0
max arbitration micros: 72
min symbol latency: 5
max symbol latency: 50
scan: finished
reconnects: 0
masters: 3
messages: 247
conditional: 3
poll: 182
update: 10
address 00: master #1
address 03: master #11
address 08: slave #11, scanned "MF=Vaillant;ID=BAI00;SW=0107;HW=7503", loaded "vaillant/bai.308523.inc", "vaillant/08.bai.csv"
address 31: master #8, ebusd
address 36: slave #8, ebusd, scanning]
Hope this raw data helps pin down the exact B509 write payload format for the SW0107 firmware!

**Comment by MarkBovee** [comment]
Thanks — this is exactly what we needed to pin down, and your reads/state-sync confirmation is very useful. The write failure is now understood and fixed for the next release.

Root cause: the runtime writable redefinition of `HeatingSwitch` / `HwcSwitch` used an `onoff` field type that is not available in the runtime define context, so ebusd rejected the element lookup with `ERR: element not found`. The write never reached the bus — which is also why a manual terminal write failed the same way. Additionally, the write message lacked the `0e` write-prefix byte that the upstream product-specific BAI includes use (`0d` for read, `0e` for write).

**v1.8.3 redefines the switches with the upstream-convention layout** (`0eF203` / `0eF303`, explicit UCH on-off encoding), so element lookup succeeds and the write telegram is actually sent.

When v1.8.3 is out, please test a toggle again. If the write is accepted but the boiler still does not react, run the **export discovery dump** service (`vaillant_ebus.export_discovery_dump`, `grab_duration: 30`) while toggling a switch, and attach the dump — we can then confirm whether the boiler applies the write or ignores the telegram.

**Comment by waphbs** [comment]
Hi @MarkBovee,

Great news! Control is completely working in v1.8.3!

Toggling the Heating Switch and DHW Switch in Home Assistant now physically turns the eloBLOCK VE 28 on and off as expected. The B509 write-prefix (0e) fix completely resolved the hardware execution issue!

There is just one minor UI behavior observation in Home Assistant regarding state synchronization:

UI Bounce Behavior: When I toggle a switch (e.g., from OFF to ON), the boiler receives the command and physically turns ON immediately. However, the switch entity in the HA UI immediately bounces back to OFF for tens of seconds before finally updating to ON on the next ebusd poll cycle.

Likely Cause: Right after executing async_turn_on / async_turn_off, HA immediately queries ebusd for the entity state. Because ebusd has not yet refreshed its cached read state from the bus, it returns the old pre-write value, causing the HA switch UI to temporarily revert until the next read poll occurs.

Suggestion: Enabling optimistic state updates (or setting the local entity state directly on service call until the next poll) in the integration should resolve this temporary UI bounce.

Thank you so much for your persistent investigation and fixes—full control over the eloBLOCK VE 28 is now achieved!

**Comment by MarkBovee** [comment]
## Verified fixed — closing

@waphbs confirmed in the latest test that control is **completely working in v1.8.3** on the eloBLOCK VE 28 (BAI00 SW0107 / HW7503): toggling `Heating Switch` and `DHW Switch` in Home Assistant now physically turns the boiler on and off. The B509 write-prefix (`0e`) fix resolved the hardware execution issue.

State reads/state-sync also confirmed working and tracked live from the physical unit.

The only remaining item is the temporary UI bounce-back after a toggle (the entity reverts to the old value for a few seconds until the next ebusd poll). Since the control path itself is verified working, that cosmetic concern is tracked separately as a feature request in #133 rather than blocking this issue.

Thanks again @waphbs for the detailed ebusctl output — it was exactly what pinned down the write layout.

**Comment by MarkBovee** [comment]
Control confirmed working in v1.8.3; UI bounce-back follow-up tracked in #133.

**Comment by IvanSCollapo** [comment]
Hi Mark,

I'm running a Protherm Ray 9 KE (BAI00, SW0107/HW7503 — same family as your eloBLOCK VE28 work) via ebusd, controlled by a small custom daemon. Your issue #111 was extremely helpful: the HeatingSwitch/HwcSwitch runtime -def writes at 0eF203/0eF303 work reliably on this firmware and don't lock the panel, unlike SetMode.

I'm now trying to go one step further: write FlowTempDesired (d.05) so my daemon can keep the panel's own setpoint in sync with the target it's computing, instead of relying on it being set manually. Right now, whenever the panel setpoint sits noticeably above my daemon's target, the boiler's own internal control seems to largely ignore the PartloadHcKW ceiling I write and chases the panel value instead — so closing this gap would make the whole control loop much more reliable.

What I've tried so far, all against the live unit:

The same 0d→0e address-swap convention that works for PartloadHcKW (read 0d0704, write 0e0704, both native entries in the stock CSV): tried a runtime -def write to 0e3900 (read side is b509,0d3900, type D2C). ebusctl write returns done, but a subsequent read still shows the old value — the boiler never applies it. Same failure signature as [ebusd-configuration#385](https://github.com/john30/ebusd-configuration/issues/385).
Noted your issue #111's own title ("SetModeOverride accepted but has no effect on BAI00 SW0107/HW7503") and issue #103 marking FlowTempDesired as read-only for this hardware — so I haven't tried routing it through SetMode, since on this exact firmware that's both apparently ineffective for flowtempdesired and the one thing I've confirmed independently locks the physical control panel (any SetMode write with a defined hcmode drops modulation to ~12%/1kW and locks the panel until a manual reset).
FlowsetHcMax/FlowTempMax (d.71) is writable and takes effect — so it seems specifically the live setpoint (d.05), not every d.XX parameter, that's locked down.
Protherm's own tech support had no information on this.

Is there a known write path for FlowTempDesired on this specific firmware (different address, different type encoding — I noticed the SetMode-embedded flowtempdesired field is D1C rather than the D2C the standalone read message uses, in case that's a clue), or is this genuinely not achievable on BAI00 SW0107/HW7503 with current knowledge? Happy to test anything you'd want to try against the live unit and report back results either way.

Thanks for the work you've already put into this hardware — it's what made the switch controls possible in the first place.

Best,
Ivan

**Comment by anzman991** [comment]
Another BAI00 data point — eloBLOCK VE21 (21 kW)

Following up on the HeatingSwitch/HwcSwitch discussion with @IvanSCollapo — I'm on a very similar unit:

Device: Vaillant eloBLOCK VE21 (21 kW, 9-step power modulation, 2.33 kW/step)
Scan result: MF=Vaillant;ID=BAI00;SW=0108;HW=7503 (one firmware revision newer than the SW0107/HW7503 already discussed here)
ebusd: 26.1.26.1, eBUS Adapter Shield C6 (WiFi, ens: enhanced TCP)
Integration: vaillant-ebus 1.9.4
I can confirm HeatingSwitch and HwcSwitch are live-readable on my unit too and reflect real state (HeatingSwitch=on, HwcSwitch=off at time of testing), matching what's reported here.

I tried reproducing the write side using the 0d→0e address-swap convention mentioned by Ivan (read side 0df203 → write side 0ef203 for HeatingSwitch), issuing a raw hex write via ebusctl write -h 08b509040ef20301, but got ERR: element not found — so either my raw hex framing is wrong (source/length byte placement) or a proper runtime -def message definition is needed first rather than a bare -h write. If either of you has the exact working ebusctl invocation (runtime -def line + write command) for HeatingSwitch/HwcSwitch on this hardware, I'd be glad to test it against my live unit and report back.

My end goal is the same class of problem as Ivan's PartloadHcKW work: I need reliable read+write on the power modulation ceiling (D.00/D.77) to cap my eloBLOCK's output at a fixed step (≤ step 4, 9.33 kW) as part of a solar-production-based load-management automation — so any progress on either the switch controls or the Partload write path is very useful to me.

Happy to run any diagnostic commands (find -v, export_discovery_dump, etc.) against my live BAI00 SW0108/HW7503 unit if that helps narrow this down.

**Comment by MarkBovee** [comment]
Thanks for adding both BAI00 data points.

The verified result for #111 remains the `HeatingSwitch` / `HwcSwitch` control path on BAI00 SW0107 / HW7503. If you are testing this through the integration, please update to the latest release, **v1.9.4**, before comparing the behavior.

The Protherm SW0107 and eloBLOCK SW0108 reports are useful follow-up evidence, but they do not establish a working `FlowTempDesired` write path or a portable raw `ebusctl write -h` command. I won't suggest either based on these captures alone. `FlowTempDesired` needs a separate hardware- and firmware-specific investigation.

**Comment by IvanSCollapo** [comment]
@anzman991 Here's exactly what works on my BAI00 SW0107/HW7503 (Protherm Ray 9 KE). Two things likely explain your ERR: element not found:

1. ebusd needs --enabledefine active before write -def will work at all. In my docker-compose:


environment:
  EBUSD_ENABLEDEFINE: ""   # must be an EMPTY string, not "1" - it's a
                            # boolean-only flag, "1" crash-loops ebusd
                            # with "invalid argument in env"
  EBUSD_ACCESSLEVEL: "*"
2. write -h (raw hex) is the wrong tool here — you need a full runtime message definition first, then a normal write -def against it. I never got a bare hex write to work either. Here's the exact working invocation:


ebusctl write -def "wi,bai,HeatingSwitchCtl,,,08,b509,0ef203,value,,UCH,0=off;1=on" 1
ebusctl write -def "wi,bai,HwcSwitchCtl,,,08,b509,0ef303,value,,UCH,0=off;1=on" 1
(1 = on, 0 = off — reissue the same -def line each time, it's cheap, ebusd just re-registers the same definition.)

One correction on your framing, in case it matters for your own reverse-engineering: I didn't derive 0eF203/0eF303 from a 0d-prefixed read counterpart via address-swapping — HeatingSwitch/HwcSwitch never had a documented d.XX read address to swap in the first place, I got those write addresses directly from Mark's original findings in this issue. The 0d→0e swap convention is something I later found does work for genuine d.XX EEPROM parameters (PartloadHcKW = d.00, confirmed both read 0d0704 and a native w,bai,PartloadHcKW,...,0e0704,... entry already exists in the stock CSV — no -def needed for that one, plain write -c bai PartloadHcKW <kw> just works). But the same convention does not generalize reliably — it's exactly what failed for FlowTempDesired (d.05) on my unit (write returns done, boiler doesn't apply it), so I wouldn't assume it'll work for your D.00/D.77 goal either without testing it directly the way you're doing.

Given PartloadHcKW writes cleanly for me with zero -def tricks on the stock CSV, if D.00/D.77 isn't writing for you, I'd first check whether your exact product CSV (bai.0010...inc) actually ships a native w,bai,... entry for it the way mine does — worth an ebusctl find -c bai -f -a -d | grep -i partload on your unit to compare. Happy to keep comparing notes — let me know if the switch commands work on SW0108.

**Comment by MarkBovee** [comment]
**v1.9.5 is now released:** https://github.com/MarkBovee/vaillant-ebus/releases/tag/v1.9.5

This release does not add a `FlowTempDesired` write path. The confirmed BAI00 control path remains `HeatingSwitch` / `HwcSwitch`; the SW0107 `0e3900` attempt still has no proven hardware effect, and SW0108 remains unverified.

If you test the integration itself, please use v1.9.5 so the result is not affected by an older version.

**Comment by anzman991** [comment]
Yes, ran the diagnostic you suggested @IvanSCollapo. Confirms your hypothesis:

ebusctl find -c bai -f -d (no -a) shows both fields, but only as r, entries:

r,bai,PartloadHcKW,d.00 Heizungsteillast,,08,b509,0d0704,value,s,UCH,,kW,
r,bai,PartloadHwcKW,d.77 Speicherteillast...,,08,b509,0d0804,value,s,UCH,,kW,

With -a (active-only), PartloadHcKW disappears entirely — not even considered valid for my product config. PartloadHwcKW stays, still read-only.

So my bai.0010....inc product CSV (mine is bai.308523.inc, DSN offset 5) simply doesn't ship a native w,bai,... entry for either field, unlike yours. That's why the 0e0704 -def write is accepted by ebusd but never reaches the actual device logic correctly — I'm guessing at an address the boiler's own DSN variant doesn't recognize as the write command for this parameter, rather than hitting a "real" but rejected write.

Given this, my address is essentially a blind guess with no CSV precedent to anchor it, unlike the 0d→0e switch case where the read address at least gave a starting point. Might need someone with write access to a genuine product-specific bai.0010...inc-style file (or a full protocol dump on a BAI00 unit where PartloadHcKW is confirmed writable) to find the right offset for the 308523/SW0108 variant.

Haven't tested the v1.9.5 switch entities yet — will report back on that separately.
